version: '3'

services:
  swoole:
    image: swoole:4.2.3
    environment:
      TZ: Asia/Taipei
    volumes:
      - .:/var/www/html/
    ports:
      - 8886:80
    stdin_open: true 
    tty: true
    privileged: true
  redis:
    image: redis
    expose:
      - "6379"
  mysql:
    image: mysql:5.5
    environment:
      TZ: Asia/Taipei
    expose:
      - "3306"
    environment:
      TZ: Asia/Taipei
      MYSQL_ROOT_PASSWORD: '1234'